name: dev_env
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - arrow-cpp=16.1.0
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - black=24.8.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.3.1
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - datasets=2.19.1
  - dbus=1.13.18
  - dill=0.3.8
  - expat=2.6.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - flake8=7.1.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libpq=17.0
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mccabe=0.7.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - nltk=3.9.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.15
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.3
  - pathspec=0.10.3
  - pcre2=10.42
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - ply=3.11
  - propcache=0.2.0
  - psutil=5.9.0
  - pyarrow=16.1.0
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=7.4.4
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - s2n=1.3.27
  - safetensors=0.4.5
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - textblob=0.18.0.post0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tokenizers=0.20.1
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - transformers=4.45.2
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wheel=0.44.0
  - wordcloud=1.9.3
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - ruff==0.8.1